service: LearnStepFunctions

custom:
  accountId: 165940758985
  attackMultiplierService: AttackMultiplierLambda
  defenseMultiplierService: DefenseMultiplierLambda
  calculateResultService: CalculateAttackResultLambda

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-admin-vgaltes
  region: us-east-1
  stage: dev
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "states:StartExecution"
       Resource: ${self:resources.Outputs.Rpg.Value}

functions:
  performAttack:
    handler: handler.performAttack
    events:
        - http:
            path: performAttack
            method: POST
    environment:
      rpg_arn: ${self:resources.Outputs.Rpg.Value}

stepFunctions:
  stateMachines:
    rpg:
      name: Rpg
      definition:
        StartAt: Attack
        States:
          Attack:
            Type: Pass
            Next: CalculateMultipliers
          CalculateMultipliers:
            Type: Parallel
            Branches:
            - StartAt: AttackMultiplier
              States:
                AttackMultiplier:
                  Type: Task
                  Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:custom.attackMultiplierService}-${opt:stage}-AttackMultiplier
                  End: true
            - StartAt: DefenseMultiplier
              States:
                DefenseMultiplier:
                  Type: Task
                  Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:custom.defenseMultiplierService}-${opt:stage}-DefenseMultiplier
                  End: true
            Next: CalculateAttackResult
          CalculateAttackResult:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:custom.calculateResultService}-${opt:stage}-calculateAttackResult
            Next: IsEnemyAlive
          IsEnemyAlive:
            Type: Choice
            Choices:
              - Variable: $.Defense.Player.Live
                NumericGreaterThan: 0
                Next: Alive
              - Variable: $.Defense.Player.Live
                NumericLessThanEquals: 0
                Next: Dead
          Alive:
            Type: Fail
            Cause: "You haven't killed the enemy"
          Dead:
            Type: Succeed
      events:
        - http:
            path: attack
            method: POST

resources:
  Outputs:
    Rpg:
      Description: The ARN of the state machine
      Value:
        Ref: Rpg

plugins:
  - serverless-step-functions
