service: LearnStepFunctions

provider:
  name: aws
  runtime: dotnetcore1.0
  profile: serverless-admin-vgaltes
  region: us-east-1
  stage: dev

stepFunctions:
  stateMachines:
    rpg:
      definition:
        StartAt: Attack
        States:
          Attack:
            Type: Pass
            Next: CalculateMultipliers
          CalculateMultipliers:
            Type: Parallel
            Branches:
            - StartAt: AttackMultiplier
              #C#
              States:
                AttackMultiplier:
                  Type: Pass
                  End: true
            - StartAt: DefenseMultiplier
              #Python
              States:
                DefenseMultiplier:
                  Type: Pass
                  End: true
            Next: CalculateAttackResult
          CalculateAttackResult:
            #Javascript
            #Errors
            Type: Pass
            InputPath: $[0]
            Next: IsEnemyAlive
          IsEnemyAlive:
            Type: Choice
            Choices:
              - Variable: $.value
                NumericGreaterThan: 0
                Next: Alive
              - Variable: $.value
                NumericLessThanEquals: 0
                Next: Dead
          Alive:
            Type: Fail
            Cause: "You haven't killed the enemy"
          Dead:
            Type: Succeed

plugins:
  - serverless-step-functions
